
openapi: 3.0.0
info:
  title: Service Account
  version: 1.1.0
servers:
  - url: http://dev-service-account.io/api/v1
    description: Test server

paths:
  /accounts/all:
    get:
      tags:
        - Accounts
      summary: Получение списка счетов
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    
  /accounts:  
    post:
      tags:
        - Accounts
      summary: Открытие нового счета
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'

  /accounts/{accountId}:
    get:
      tags:
        - Accounts
      summary: Получение детальной информации по счету
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string($uuid)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetails'
    put:
      tags:
        - Accounts
      summary: Изменение параметров счета
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string($uuid)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountUpdateRequest'
      responses:
        '200':
          description: Account updated successfully

  /accounts/{accountId}/close:
    delete:
      tags:
        - Accounts
      summary: Закрытие счета
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string($uuid)
      responses:
        '204':
          description: Account closed successfully

  /accounts/{accountId}/blocking:
    put:
      tags:
        - Accounts
      summary: Установка или снятие блокировки на счет
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: string($uuid)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountBlockRequest'
      responses:
        '200':
          description: Operation successfully

components:
  schemas:
    Account:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        accountNumber:
          type: string
        currency:
          type: string
        currentBalance:
          type: integer 
        openingDateTime:
          type: string
          format: date
        closedDateTime:
          type: string
          format: date

    AccountDetails:
      allOf:
        - $ref: '#/components/schemas/Account'
        - type: object
      properties:
        client:
          type: object
          properties:
            clientId:
              type: string
            fullName:
              type: string
            isJuridical:
              type: boolean
        document:
          type: object
          properties:
            documentId:
              type: string
            documentNumber:
              type: string
            descripption:
              type: string
            registrationDateTime:
              type: string
              format: date
        isBlock:
          type: boolean
        descripption:
          type: string 

    NewAccountRequest:
      type: object
      properties:
        clientId:
          type: string
        currency:
          type: string
        description:
          type: string

    AccountUpdateRequest:
      type: object
      properties:
        description:
          type: string

    AccountBlockRequest:
      type: object
      properties:
        isBlock:
          type: boolean

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token

security:
  - BearerAuth: []